#!/usr/bin/env groovy

pipeline {
    agent any

    options {
        ansiColor("xterm")
    }

    stages {
        stage("Checkout relevant git repo") {
            steps {
                sh "sudo rm -rf * .[a-z0-9_]*"
                checkout scm
            }
        }

        stage("Build cmc service") {
            steps {
                sh "cd services/cmc && ./release.sh"
            }
        }
    }
}
