- name: "Provisioning the Shore"
  hosts: localhost
  remote_user: pandora
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - { role: postgresql, tags: postgresql}
    - { role: virtlyst, tags: virt_deployment}      

